using Terraria.ModLoader;

namespace AssortedCrazyThings
{
    public class PetPlayer : ModPlayer
    {
		public bool Pigronata = false;
		public bool Abeemination = false;
		public bool CuteSlimeYellowNew = false;
		public bool CuteSlimeXmasNew = false;
		public bool CuteSlimeRedNew = false;
		public bool CuteSlimeRainbowNew = false;
		public bool CuteSlimePurpleNew = false;
		public bool CuteSlimePinkNew = false;
		public bool CuteSlimeGreenNew = false;
		public bool CuteSlimeBlueNew = false;
		public bool CuteSlimeBlackNew = false;
		public bool DocileMechanicalLaserEyeGreen = false;
		public bool DocileMechanicalLaserEyePurple = false;
		public bool DocileMechanicalLaserEyeRed = false;
		public bool OrigamiCrane = false;
		public bool MiniMegalodon = false;
		public bool SmallMegalodon = false;
		public bool CuteSlimeXmas = false;
		public bool YoungHarpy = false;
		public bool CuteGastropod = false;
		public bool YoungWyvern = false;
		public bool BabyIchorSticker = false;
		public bool LifelikeMechanicalFrog = false;
		public bool CuteSlimeBlue = false;
		public bool CuteSlimeGreen = false;
		public bool CuteSlimePink = false;
		public bool CuteSlimeBlack = false;
		public bool CuteSlimePurple = false;
		public bool CuteSlimeRed = false;
		public bool CuteSlimeYellow = false;
		public bool CuteSlimeRainbow = false;
		public bool ChunkyandMeatball = false;
		public bool DemonHeart = false;
		public bool BrainofConfusion = false;
		public bool AlienHornet = false;
		public bool DocileDemonEyeRed = false;
		public bool DocileFracturedEyeRed = false;
		public bool DocileDemonEyeGreen = false;
		public bool DocileFracturedEyeGreen = false;
		public bool DocileDemonEyePurple = false;
		public bool DocileFracturedEyePurple = false;
		public bool DocileMechanicalEyeRed = false;
		public bool DocileMechanicalEyeGreen = false;
		public bool DocileMechanicalEyePurple = false;
		public bool DetachedHungry = false;
		public bool BabyOcram = false;
		public bool CursedSkull = false;
		public bool BabyCrimera = false;
		public bool VampireBat = false;
		public bool TorturedSoul = false;
		public bool EnchantedSword = false;
        public bool GobletPet = false;
        public bool SoulLightPet = false;
        public bool DocileDemonEye = false;

        public override void ResetEffects()
		{
			Pigronata = false;
			Abeemination = false;
			CuteSlimeYellowNew = false;
			CuteSlimeXmasNew = false;
			CuteSlimeRedNew = false;
			CuteSlimeRainbowNew = false;
			CuteSlimePurpleNew = false;
			CuteSlimePinkNew = false;
			CuteSlimeGreenNew = false;
			CuteSlimeBlueNew = false;
			CuteSlimeBlackNew = false;
			DocileMechanicalLaserEyeGreen = false;
			DocileMechanicalLaserEyePurple = false;
			DocileMechanicalLaserEyeRed = false;
			OrigamiCrane = false;
			MiniMegalodon = false;
			SmallMegalodon = false;
			CuteSlimeXmas = false;
			YoungHarpy = false;
			CuteGastropod = false;
			YoungWyvern = false;
			BabyIchorSticker = false;
			LifelikeMechanicalFrog = false;
			CuteSlimeBlue = false;
			CuteSlimeGreen = false;
			CuteSlimePink = false;
			CuteSlimeBlack = false;
			CuteSlimePurple = false;
			CuteSlimeRed = false;
			CuteSlimeYellow = false;
			CuteSlimeRainbow = false;
			ChunkyandMeatball = false;
			DemonHeart = false;
			BrainofConfusion = false;
			AlienHornet = false;
			DocileDemonEyeRed = false;
			DocileFracturedEyeRed = false;
			DocileDemonEyeGreen = false;
			DocileFracturedEyeGreen = false;
			DocileDemonEyePurple = false;
			DocileFracturedEyePurple = false;
			DocileMechanicalEyeRed = false;
			DocileMechanicalEyeGreen = false;
			DocileMechanicalEyePurple = false;
			DetachedHungry = false;
			BabyOcram = false;
			CursedSkull = false;
			BabyCrimera = false;
			VampireBat = false;
			TorturedSoul = false;
			EnchantedSword = false;
            GobletPet = false;
            SoulLightPet = false;
            DocileDemonEye = false;
        }	
	}
}